
racking_descriptions_status.coffee: racking_descriptions_status_base.coffee \
../settings.coffee \
../urls.coffee
	cat ../settings.coffee \
	../urls.coffee \
	racking_descriptions_status_base.coffee > racking_descriptions_status.coffee