

pricelist_upload_status.coffee: pricelist_upload_status_base.coffee \
../settings.coffee \
../urls.coffee \
templates/products.coffee
	cat ../settings.coffee \
	../urls.coffee \
	templates/products.coffee \
	pricelist_upload_status_base.coffee > pricelist_upload_status.coffee