name             'renesola'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures renesola'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'apt'
depends 'apache2'
depends 'zlib'
depends 'postgresql'
depends 'git'
depends 'php'
depends 'redis'
depends 'rabbitmq'
depends 'redis'
depends 'nodejs'
depends 'python'
